In [41]:
import pandas as pd

bangalore_df = pd.read_excel('Dataset/bangalore_cars.xlsx')
jaipur_df =  pd.read_excel('Dataset/jaipur_cars.xlsx')
chennai_df =  pd.read_excel('Dataset/chennai_cars.xlsx')
hyderabad_df =  pd.read_excel('Dataset/hyderabad_cars.xlsx')
kolkata_df =  pd.read_excel('Dataset/kolkata_cars.xlsx')
delhi_df =  pd.read_excel('Dataset/delhi_cars.xlsx')

In [42]:
# Adding the Column for the DataSet to mention the City

chennai_df['City'] = 'Chennai'
delhi_df['City'] = 'Delhi'
hyderabad_df['City'] = 'Hyderabad'
jaipur_df['City'] = 'Jaipur'
kolkata_df['City'] = 'Kolkata'
bangalore_df['City'] = 'Bangalore'

In [43]:
df1 = pd.concat([bangalore_df,chennai_df],ignore_index = True)
df2 = pd.concat([delhi_df,hyderabad_df],ignore_index = True)
df3 = pd.concat([jaipur_df,kolkata_df], ignore_index = True)
df4 = pd.concat([df1,df2],ignore_index = True)
final_df = pd.concat([df4,df3],ignore_index = True)
final_df.shape

(8369, 6)

In [44]:
final_df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links,City
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Bangalore
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Bangalore
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
...,...,...,...,...,...,...
8364,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8365,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8366,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8367,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8368,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata

In [46]:
new_car_detail_df = pd.DataFrame(final_df['new_car_detail'])
json_normalized = pd.json_normalize(new_car_detail_df['new_car_detail'].apply(eval))

In [47]:
new_car_detail_df

                                         new_car_detail
0     {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1     {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2     {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
3     {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
4     {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
...                                                 ...
8364  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
8365  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
8366  {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
8367  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
8368  {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...

[8369 rows x 1 columns]

In [25]:
import pandas as pd

df = pd.DataFrame(final_df['new_car_detail'])
df1 = pd.DataFrame(final_df['new_car_overview'])
df2 = pd.DataFrame(final_df['new_car_feature'])
Json_normalized = pd.json_normalize(df['new_car_detail'].apply(eval))
Json_normalized1 = pd.json_normalize(df1['new_car_overview'].apply(eval))
Json_normalized2 = pd.json_normalize(df2['new_car_feature'].apply(eval))
# Json_normalized = pd.json_normalize(df)
df = pd.concat([df.drop(columns=["new_car_detail"]), Json_normalized], axis=1)
df1 = pd.concat([df1.drop(columns=["new_car_overview"]), Json_normalized1], axis=1)
df2 = pd.concat([df2.drop(columns=["new_car_feature"]), Json_normalized2], axis=1)

print(df)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback  1,20,000       Manual        3  3rd Owner
1      0  Petrol        SUV    32,706       Manual        2  2nd Owner
2      0  Petrol  Hatchback    11,949       Manual        1  1st Owner
3      0  Petrol      Sedan    17,794       Manual        1  1st Owner
4      0  Diesel        SUV    60,000       Manual        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
8364   0  Petrol  Hatchback    10,000       Manual        1  1st Owner
8365   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
8366   0  Petrol      Sedan    50,000    Automatic        3  3rd Owner
8367   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
8368   0  Diesel        SUV  1,20,000       Manual        2  2nd Owner

                oem                  model  modelYear  centralVariantId  \
0            Maruti         Maruti Celerio       2015              3979
1              Ford          Ford Ecosport       2018              6087
2              Tata             Tata Tiago       2018              2983
3           Hyundai          Hyundai Xcent       2014              1867
4            Maruti     Maruti SX4 S Cross       2015              4277
...             ...                    ...        ...               ...
8364         Maruti         Maruti Celerio       2022              8682
8365         Maruti        Maruti Alto 800       2014              3943
8366  Mercedes-Benz  Mercedes-Benz C-Class       2011              4672
8367         Maruti            Maruti Ritz       2012              4144
8368        Renault         Renault Duster       2017              5048

                   variantName        price priceActual priceSaving  \
0                          VXI     ₹ 4 Lakh
1     1.5 Petrol Titanium BSIV  ₹ 8.11 Lakh
2              1.2 Revotron XZ  ₹ 5.85 Lakh
3           1.2 Kappa S Option  ₹ 4.62 Lakh
4                DDiS 200 Zeta  ₹ 7.90 Lakh
...                        ...          ...         ...         ...
8364                  ZXI BSVI  ₹ 5.10 Lakh
8365                       LXI  ₹ 1.80 Lakh
8366        C 200 CGI Elegance  ₹ 5.50 Lakh
8367                       ZXi  ₹ 1.40 Lakh
8368      110PS Diesel RxZ AWD     ₹ 5 Lakh

     priceFixedText                                trendingText.imgUrl  \
0              None  https://stimg.cardekho.com/used-cars/common/ic...
1              None  https://stimg.cardekho.com/used-cars/common/ic...
2              None  https://stimg.cardekho.com/used-cars/common/ic...
3              None  https://stimg.cardekho.com/used-cars/common/ic...
4              None  https://stimg.cardekho.com/used-cars/common/ic...
...             ...                                                ...
8364           None  https://stimg.cardekho.com/used-cars/common/ic...
8365           None  https://stimg.cardekho.com/used-cars/common/ic...
8366           None  https://stimg.cardekho.com/used-cars/common/ic...
8367           None  https://stimg.cardekho.com/used-cars/common/ic...
8368           None  https://stimg.cardekho.com/used-cars/common/ic...

     trendingText.heading                    trendingText.desc
0           Trending Car!  High chances of sale in next 6 days
1           Trending Car!  High chances of sale in next 6 days
2           Trending Car!  High chances of sale in next 6 days
3           Trending Car!  High chances of sale in next 6 days
4           Trending Car!  High chances of sale in next 6 days
...                   ...                                  ...
8364        Trending Car!  High chances of sale in next 6 days
8365        Trending Car!  High chances of sale in next 6 days
8366        Trending Car!  High chances of sale in next 6 days
8367        Trending Car!  High chances of sale in next 6 days
8368        Trending Car!  High chances of sale in next 6 days

[8369 rows x 19 columns]

In [16]:
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,₹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,₹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,₹ 5.85 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,₹ 4.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,₹ 7.90 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,8682,ZXI BSVI,₹ 5.10 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8365,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,3943,LXI,₹ 1.80 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8366,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,4672,C 200 CGI Elegance,₹ 5.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8367,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,4144,ZXi,₹ 1.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8368,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,5048,110PS Diesel RxZ AWD,₹ 5 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [21]:
df1

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': 'Sept 2...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'Dec 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
...,...,...,...
8364,Car overview,"[{'key': 'Registration Year', 'value': '2022',...",None
8365,Car overview,"[{'key': 'Registration Year', 'value': '2014',...",None
8366,Car overview,"[{'key': 'Registration Year', 'value': '2011',...",None
8367,Car overview,"[{'key': 'Registration Year', 'value': '2012',...",None
8368,Car overview,"[{'key': 'Registration Year', 'value': '2017',...",None

In [26]:
df2

,heading,top,data,commonIcon
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...,...,...,...,...
8364,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
8365,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
8366,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
8367,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
8368,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [22]:

overview_top = df1['top'].apply(
    lambda x: {d['key']: d['value'] for d in x}
)

overview_top = pd.json_normalize(overview_top)

In [29]:
print(df2['top'][0])

[{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Head Lights'}, {'value': 'Manually Adjustable Exterior Rear View Mirror'}, {'value': 'Centeral Locking'}, {'value': 'Child Safety Locks'}]

In [33]:
feature_top = df2['top'].apply(
    lambda x: { d['value'] for d in x}
)

# feature_top = pd.json_normalize(feature_top)

In [34]:
feature_top

0       {Centeral Locking, Child Safety Locks, Power S...
1       {Centeral Locking, Fog Lights Front, Power Ste...
2       {Centeral Locking, Fog Lights Front, Power Ste...
3       {Centeral Locking, Fog Lights Front, Power Ste...
4       {Radio, Centeral Locking, Fog Lights Front, Po...
                              ...
8364    {Radio, Centeral Locking, Power Adjustable Ext...
8365    {Day Night Rear View Mirror, Passenger Side Re...
8366    {Brake Assist, Fog Lights Front, Power Steerin...
8367    {Centeral Locking, Fog Lights Front, Power Ste...
8368    {Brake Assist, Fog Lights Front, Power Steerin...
Name: top, Length: 8369, dtype: object

In [36]:
final_df['new_car_specs']
df3 = pd.DataFrame(final_df['new_car_specs'])
Json_normalized3 = pd.json_normalize(df3['new_car_specs'].apply(eval))
df3 = pd.concat([df3.drop(columns=["new_car_specs"]), Json_normalized3], axis=1)

In [37]:
df3

,heading,top,data,commonIcon
0,Specifications,"[{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
2,Specifications,"[{'key': 'Mileage', 'value': '23.84 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
3,Specifications,"[{'key': 'Mileage', 'value': '19.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
4,Specifications,"[{'key': 'Mileage', 'value': '23.65 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
...,...,...,...,...
8364,Specifications,"[{'key': 'Mileage', 'value': '25.24 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
8365,Specifications,"[{'key': 'Mileage', 'value': '22.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
8366,Specifications,"[{'key': 'Mileage', 'value': '11.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
8367,Specifications,"[{'key': 'Mileage', 'value': '18.5 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
8368,Specifications,"[{'key': 'Mileage', 'value': '19.72 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",

In [38]:
specs_top = df3['top'].apply(
    lambda x: {d['key']: d['value'] for d in x}
)

In [40]:
st = pd.json_normalize(specs_top)
st

         Mileage   Engine  Max Power    Torque Seats Wheel Size
0      23.1 kmpl   998 CC   67.04bhp      90Nm     5        NaN
1        17 kmpl  1497 CC  121.31bhp     150Nm     5         16
2     23.84 kmpl  1199 CC      84bhp     114Nm     5         14
3      19.1 kmpl  1197 CC   81.86bhp  113.75Nm     5         14
4     23.65 kmpl  1248 CC    88.5bhp     200Nm     5         16
...          ...      ...        ...       ...   ...        ...
8364  25.24 kmpl   998 CC   65.71bhp      89Nm     5        NaN
8365  22.74 kmpl   796 CC    47.3bhp      69Nm     5        NaN
8366  11.74 kmpl  1796 CC     186bhp     285Nm     5         17
8367   18.5 kmpl  1197 CC   85.80bhp     114Nm     5         14
8368  19.72 kmpl  1461 CC  108.45bhp     245Nm     5         16

[8369 rows x 6 columns]